blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('login/', views.Login, name='login'),
    path('register/', views.Register, name='register'),
    path('friends/', views.Friends_view, name='friends'),
    path('profile/<int:user_id>', views.Profile_view, name='profile'),
    path('profile/settings', views.Profile_settings, name="profile_settings"),
    path('logout/', views.Logout, name='logout'),
    path('posts/settings/<int:id>', views.Post_settings, name='post_settings'),
    path('chat/<str:room_name>/', views.Room_view, name='chat_room'),
    path('chat/', views.Chat_view, name='chat'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import auth
from django.utils import timezone
import json
from django.contrib.humanize.templatetags import humanize
from io import BytesIO
from django.core.files import File
from PIL import Image

def UserMethods():
    def get_date(self):
        return humanize.naturaltime(self.date_joined)
    auth.models.User.add_to_class("get_date", get_date)
UserMethods()

def make_image(image, size):
    img = Image.open(image)
    img.convert('RGB')
    img.thumbnail(size)
    thumb_io = BytesIO()
    img.save(thumb_io, 'JPEG', quality=85)
    image = File(thumb_io, name=image.name)
    return image


class Profile(models.Model):
    GENDER_CHOICES = (
        ('Male', "Male"),
        ('Female', "Female"),
        ('Prefer not to say', "Prefer not to say"),
    )
    COUNTRY_CHOICES = (
        ('Hungary', "Hungary"),
        ('United States', "United States"),
    )

    user = models.OneToOneField(User, default=None, null=True, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, blank=True, null=True)
    country = models.CharField(max_length=50, choices=COUNTRY_CHOICES, blank=True, null=True)
    image = models.ImageField(upload_to="static/pics/profile_pics/", blank=True, null=True)
    background = models.ImageField(upload_to="static/pics/bg_pics/", blank=True)

    def save(self, *args, **kwargs):
        self.image = make_image(image=self.image, size=(100, 100))
        super().save(self, *args, **kwargs)

    def __str__(self):
        return f"{self.user}'s profile"


class Friend(models.Model):
    STATUS_CHOICES = (
        ('Sent', 'Sent'),
        ('Accepted', 'Accepted'),
        ('Declined', 'Declined'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user", default=None)
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend", default=None)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, null=True)
    date_created = models.DateTimeField(default=timezone.now)

    def get_date(self):
        return humanize.naturaltime(self.date_created)

    def __str__(self):
        return f"{self.user} and {self.friend}"


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def get_date(self):
        return humanize.naturaltime(self.date_posted)

    def __str__(self):
        return f"{self.author}'s. {self.date_posted}"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name="fasz", default=None)

    def get_date(self):
        return humanize.naturaltime(self.date_posted)

    def __str__(self):
        return f"{self.post} - {self.author}"

    class Meta:
        ordering = ["-date_posted"]


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes", default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes", default=None)

    def __str__(self):
        return f"{self.user} liked {self.post}"



class Room(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator", default=None, null=True)
    users = models.ManyToManyField(User, default=None)
    title = models.CharField(max_length=250, default=None)
    limit = models.IntegerField(null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    def get_date(self):
        return humanize.naturaltime(self.date_created)

    def __str__(self):
        return self.title


class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def get_date(self):
        return humanize.naturaltime(self.date_posted)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import Room, User, Post, Like, Message, Friend, Comment
from blog.forms import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import os
from django.db.models import Q
import json
from django.core.files.storage import default_storage

@login_required
def Home(request):

    if request.is_ajax() and request.method == "POST":
        if 'like' in request.POST:
            post = Post.objects.get(id=request.POST["post_id"])
            user = get_object_or_404(User, id=request.user.id)
            like_post(post=post, user=user)

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

        elif 'unlike' in request.POST:
            post = Post.objects.get(id=request.POST["post_id"])
            user = get_object_or_404(User, id=request.user.id)
            delete_like(post=post, user=user)

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

        elif 'comment_like' in request.POST:
            c = Comment.objects.get(id=request.POST["comment_id"])
            c.likes.add(request.user.id)

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

        elif 'comment_unlike' in request.POST:
            c = Comment.objects.get(id=request.POST["comment_id"])
            c.likes.remove(request.user.id)

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

        elif 'post_remove' in request.POST:
            post = Post.objects.get(id=request.POST["post_id"])
            post.delete()

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

        elif 'add_comment' in request.POST:
            post = Post.objects.get(id=request.POST["comment_post_id"])
            create_comment(post=post, author=request.user,content=request.POST["content"])

            data = [{}]
            response = JsonResponse(json.dumps(data, sort_keys=True, default=str, indent=4), safe=False)
            return response

    else:
        posts = Post.objects.order_by('-date_posted')
        users = User.objects.all()
        user_count = User.objects.count()
        comments = Comment.objects.all()
        friend_requests = Friend.objects.filter(friend=request.user, status="Sent").count()

        context = {
            'title': 'Home',
            'friend_requests': friend_requests,
            'posts': posts,
            'users': users,
            'user_count': user_count,
            'comments': comments,
        }
        return render(request, "blog/home.html", context)


def Login(request):

    if request.user.is_authenticated:
        messages.error(request, "You already logged in!")
        return redirect("profile", request.user.id)

    else:
        form = ""
        next = request.POST.get('next', request.GET.get('next', ''))

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                messages.success(request, "Successfully signed in!")
                if next:
                    return HttpResponseRedirect(next)
                return redirect("profile", user.id)
            else:
                form = LoginForm()
                messages.error(request, "Wrong credentials!")
        else:
            form = LoginForm()

        context = {
            'form': form,
            'title': 'Login',
        }
        return render(request, "blog/login.html", context)


def Register(request):

    context = {}

    if request.user.is_authenticated:
        messages.error(request, "You are logged in!")
        return redirect("profile", request.user.id)

    else:

        if request.is_ajax() and request.method == "POST":

            if 'Form1' in request.POST:
                form = Register1Form(request.POST)

                if form.is_valid():
                    email, first_name, last_name = form.cleaned_data.get('email'), form.cleaned_data.get('first_name'), form.cleaned_data.get('last_name')

                    request.session["r_email"] = email
                    request.session["r_first_name"] = first_name
                    request.session["r_last_name"] = last_name

                    return JsonResponse({'message': 'success'})
                else:
                    return JsonResponse({'message': form.errors})

            elif 'Form2' in request.POST:
                form = Register2Form(request.POST, request.FILES)

                if form.is_valid():
                    birth_date, image, country, gender = form.cleaned_data.get('birth_date'), form.cleaned_data.get('image'), form.cleaned_data.get('country'), form.cleaned_data.get('gender')
                    request.session["r_profile"] = create_profile(user=None, birth_date=birth_date, image=image, country=country, gender=gender)

                    return JsonResponse({'message': 'success'})
                else:
                    return JsonResponse({'message': form.errors})

            elif 'Form3' in request.POST:
                form = Register3Form(request.POST)

                if form.is_valid():
                    email = request.session["r_email"]
                    first_name = request.session["r_first_name"]
                    last_name = request.session["r_last_name"]

                    user = form.save()
                    user.refresh_from_db()
                    user = User.objects.get(username=form.cleaned_data.get("username"))

                    User.objects.filter(username=form.cleaned_data.get("username")).update(email=email, first_name=first_name, last_name=last_name)
                    Profile.objects.filter(id=request.session["r_profile"]).update(user=user)

                    messages.success(request, "Successfully created the account!")
                    return JsonResponse({'message': 'success'})
                else:
                    return JsonResponse({'message': form.errors})

        context = {
            "title": "Register",
            "form1": Register1Form,
            "form2": Register2Form,
            "form3": Register3Form,
        }

        return render(request, "blog/register.html", context)

#
# Create, Delete Functions
#

def create_profile(user, birth_date, image, country, gender):
    u = Profile(user=user, birth_date=birth_date,image=image, country=country, gender=gender)
    u.save()
    return u.id


def create_post(author, content):
    p = Post(author=author, content=content)
    p.save()


def create_friendship(user, friend):
    f = Friend(user=user, friend=friend, status="Sent")
    f.save()


def delete_friendship(user, friend):
    try:
        f = Friend.objects.get(user=user, friend=friend)
    except Friend.DoesNotExist:
        f = Friend.objects.get(user=friend, friend=user)
    f.delete()


def create_comment(post, author, content):
    p = Comment(post=post, author=author, content=content)
    p.save()


def like_post(post, user):
    l = Like(post=post, user=user)
    l.save()


def delete_like(post, user):
    l = Like.objects.filter(post=post, user=user)
    l.delete()


@login_required
def Logout(request):
    logout(request)
    messages.success(request, "Successfully logged out!")
    return HttpResponseRedirect(Login)


@login_required
def Profile_view(request, user_id):
    view_user = get_object_or_404(User, id=user_id)
    profile = request.user.profile

    if view_user:
        if request.is_ajax() and request.method == "POST":

            if 'like' in request.POST:
                post = Post.objects.get(id=request.POST["post_id"])
                user = get_object_or_404(User, id=request.user.id)
                like_post(post=post, user=user)

                data = [{}]
                response = JsonResponse(data, safe=False)
                return response

            elif 'unlike' in request.POST:
                post = Post.objects.get(id=request.POST["post_id"])
                user = get_object_or_404(User, id=request.user.id)
                delete_like(post=post, user=user)

                data = [{}]
                response = JsonResponse(data, safe=False)
                return response

            elif 'comment_like' in request.POST:
                c = Comment.objects.get(id=request.POST["comment_id"])
                c.likes.add(request.user.id)

                data = [{}]
                response = JsonResponse(data, safe=False)
                return response

            elif 'comment_unlike' in request.POST:
                c = Comment.objects.get(id=request.POST["comment_id"])
                c.likes.remove(request.user.id)

                data = [{}]
                response = JsonResponse(data, safe=False)
                return response

            elif 'new_post' in request.POST:
                create_post(author=request.user, content=request.POST["content"])

                data = [{}]
                response = JsonResponse(data, safe=False)
                return response

            elif 'post_remove' in request.POST:
                post = Post.objects.get(id=request.POST["post_id"])
                post.delete()

                data = [{}]
                response = JsonResponse(data, safe=False)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
        <meta name="description" content="A facebook clone. Made by a Dávid Várnai.">
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'pics/small_logo.png' %}">
        <title>
            {% if title %}
                PeopleBook - {{ title }}
            {% else %}
                PeopleBook
            {% endif %}
        </title>
        {% block head %}
        {% endblock %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    </head>
    <body>

        {% include "blog/navbar.html" %}

        <div class="messages container" id="alert_box">
        </div>

        {% if messages %}
            <div class="messages container">
                {% for message in messages %}
                    <div class="fixed-top alert alert-dismissible fade show {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <main role="main">
            {% block content %}
            {% endblock %}
        </main>     

        {% include "blog/footer.html" %}
        <script src="{% static '/js/main.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    </body>
</html>

blog/templates/blog/chat.html
{% extends "blog/base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/chat.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/form.css' %}" type="text/css">
    <script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">

            <div class="room-create">
                <form id="form" onsubmit="roomValidation();return false;" method="POST">
                    <div class="row">
                        {% csrf_token %}

                        <div class="col-5">
                            <p>Room name:</p>
                            <input type="text" name="title" class="input title">
                        </div>

                        <div class="col-3">
                            <p>Room limit:</p>
                            <div class="limit-wrapper">
                                <input type="number" name="limit" class="input number" value="3" max="5" min="2">
                                <button type="button" onclick="limitAdd()" class="plus"><i class="fas fa-plus"></i></button>
                                <button type="button" onclick="limitRemove()" class="minus"><i class="fas fa-minus"></i></button>
                            </div>
                            <script>
                                const limit = document.getElementsByName("limit")[0]

                                const limitAdd = () =>{
                                    if (limit.value != "5"){
                                        limit.value = parseInt(limit.value) + 1
                                    }
                                }
                                const limitRemove = () =>{
                                    if (limit.value != "2"){
                                        limit.value = parseInt(limit.value) - 1
                                    }
                                }
                            </script>
                        </div>

                        <div class="col-4">
                            <button type="submit" class="btn btn-primary createRoom" name="create_room"><i class="fas fa-plus"></i> Create Room</button>
                        </div>

                    </div>
                </form>
            </div>
            
            {% for room in rooms %}

                <div class="col-4">
                    <div class="card room-card">
                        <div class="card-header">
                            <h1>{{ room.title }}</h1>
                            <div class="room-pics row justify-content-center text-center">
                                {% for user in room.users.all %}
                                    <div class="room-div col-4">
                                        {% if forloop.counter >= 4 %}
                                        {% else %}
                                            {% if user == room.creator %}
                                                <i class="fas fa-crown"></i>
                                            {% endif %}
                                            <img src="https://storage.cloud.google.com/peoplebook/{{ user.profile.image }}" height="75" width="75" class="rounded-circle {% if room.users.count != "0" and room.users.count != "1" %}nemNulla{% else %}{% endif %}">
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="card-body">
                            {% if request.user in room.users.all %}
                                <div class="d-flex">
                                    <form action="{% url 'chat_room' room %}" id="leftForm{{ forloop.counter }}" class="rightForm">
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-external-link-square-alt"></i> Enter</button>
                                    </form>

                                    <form action="" method="POST" id="rightForm{{ forloop.counter }}" class="rightForm">
                                        {% csrf_token %}
                                        <input type="hidden" name="room_id" value="{{ room.id }}">
                                        <button type="submit" class="btn btn-danger" name="leave_room">Leave <i class="fas fa-sign-out-alt fa-lg"></i></button>
                                    </form>

                                </div>
                            {% else %}
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="room_id" value="{{ room.id }}">
                                    <button type="submit" class="btn btn-primary" name="enter_room"><i class="fas fa-sign-in-alt fa-lg"></i> Join</button>
                                </form>
                            {% endif %}
                        </div>
                        <div class="card-footer">
                            <p>Created {{ room.get_date }}</p>
                        </div>
                    </div>
                </div>

            {% empty %}

                <p>There are 0 chat rooms</p>

            {% endfor %}
        </div>
    </div>

{% endblock %}

blog/templates/blog/footer.html
<footer class="text-center text-white">
    <div class="text-center">
        <p class="p-4">© 2021 Copyright: <span style="color: var(--primary-color)">Peoplebook</span></p>
    </div>
</footer>

blog/templates/blog/post_settings.html
{% extends "blog/base.html" %}

{% load static %}
{% load widget_tweaks %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}" type="text/css">
    <style>
        .login-wrapper .form-wrapper form .input{
            max-height: 420px;
            min-height: 200px;
            padding-left: 10px;
        }
    </style>
{% endblock %}

{% block content %}
        <div class="login-wrapper">
        <div class="form-wrapper">
            <h1>Post update</h1>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label }}
                    <div class="input-container">
                        {{ field|add_class:"input" }}
                    </div>
                {% endfor %}
                <button type="submit" name="submit" class="btn btn-primary">Update</button>
            </form>
            <div class="bottom-links">
                <a href="{% url 'profile' request.user.id %}" style="font-size: 18px;"><u><i>Back</i></u></a>                        
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/posts.css' %}" type="text/css">
{% endblock %}

{% block content %}

    <h1>Post creation</h1>

{% endblock %}

blog/templates/blog/settings.html
{% extends "blog/base.html" %}

{% load static %}
{% load widget_tweaks %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <style>
        #id_image, #id_background{ display: none; }
        #id_bio{ padding-top: 8px; min-height: 80px; }
        .form-wrapper h1{ padding: 12px; padding-bottom: 0; }
        .form-wrapper form{ padding: 10px; }
        .form-wrapper hr{ margin-bottom: 20px; }
    </style>
{% endblock %}

{% block content %}

    <div class="login-wrapper">
        <div class="form-wrapper">
            <h1>Profile Update</h1>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in uform %}
                    {{ field.label }}
                    <div class="input-container">
                        {{ field|add_class:"input" }}
                        <div class="icon-wrapper">
                            <i class="
                                {% if field.label == 'Username' or field.label == 'First name' or field.label == 'Last name' %}
                                    fas fa-user
                                {% elif field.label == 'Email address' %}
                                    fas fa-envelope
                                {% elif field.label == 'Birth date' %}
                                    far fa-calendar-alt
                                {% endif %}
                            "></i>
                        </div>
                    </div>
                    {% if field.errors %}
                        <div class="alert alert-danger custom-alert">
                            {{ field.errors }} 
                            {% if field.help_text %}
                            <ul class="errorlist">
                                <li>{{ field.help_text }}</li>
                            </ul>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}

                {% for field in pform %}
                    {{ field.label }}
                    <div class="input-container">
                        {{ field|add_class:"input" }}
                        <div class="icon-wrapper">
                            <i class="
                                {% if field.label == 'Bio' %}
                                    fas fa-info-circle
                                {% elif field.label == 'Birth date' %}
                                    far fa-calendar-alt
                                {% elif field.label == 'Gender' %}
                                    fas fa-venus-mars
                                {% elif field.label == 'Country' %}
                                    fas fa-globe-europe
                                {% endif %}
                            "></i>
                        </div>
                    </div>
                    {% if field.errors %}
                        <div class="alert alert-danger custom-alert">
                            {{ field.errors }} 
                            {% if field.help_text %}
                            <ul class="errorlist">
                                <li>{{ field.help_text }}</li>
                            </ul>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
                
                {{ imgform }}
                {{ bgform }}

                <div class="input-container">
                    <button type="button" id="getImg" class="input">Upload a new image</button>
                    <div class="icon-wrapper">
                        <i class="fas fa-camera"></i>
                    </div>
                </div>

                <div class="input-container">
                <button type="button" id="getBg" class="input">Upload a new background</button>
                    <div class="icon-wrapper">
                        <i class="fas fa-image"></i>
                    </div>
                </div>

                <script>
                    var id_image = document.getElementById("id_image")
                    var getImg = document.getElementById("getImg")

                    id_image.onchange = function(){
                        if (id_image.value == ""){
                            getImg.innerHTML = "Upload a new image"
                        }
                        else{
                            getImg.innerHTML = id_image.value.split("\\").pop()
                        }
                    };

                    getImg.onclick = function(){
                        id_image.click();
                    };

                    var id_background = document.getElementById("id_background")
                    var getBg = document.getElementById("getBg")

                    id_background.onchange = function(){
                        if (id_background.value == ""){
                            getBg.innerHTML = "Upload a new image"
                        }
                        else{
                            getBg.innerHTML = id_background.value.split("\\").pop()
                        }
                    };

                    getBg.onclick = function(){
                        id_background.click();
                    };
                </script>
                
                <button type="submit" name="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>

{% endblock %}